version: '3'
services:
  todoapp-db:
    image: mongo:4.2.2
    environment:
      MONGO_INITDB_DATABASE: todoapp
    ports:
      - 27017:27017
  todoapp-frontend:
    image: todoapp-frontend:latest
    environment:
      PORT: 3000
      PROXY_API: http://todoapp-backend:8080/
    ports:
      - 3000:3000
  todoapp-backend:
    image: todoapp-backend:latest
    environment:
      MONGODB_URI: mongodb://todoapp-db:27017/todoapp
    ports:
      - 8080:8080