version: '3'
services:
  todoapp-frontend:
    image: todoapp-frontend:latest
    environment:
      PORT: 3000
      PROXY_API: http://todoapp-frontend:8080/
    ports:
      - 3000:3000
  todoapp-backend:
    image: todoapp-backend:latest
    environment:
      MONGODB_URI: mongodb+srv://<user>:<password>@<your cluster>/todo?retryWrites=true&w=majority
    ports:
      - 8080:8080